stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:20.10.8
  services:
    - docker:20.10.8-dind
  script:
    - docker build -t myproject .

test:
  stage: test
  image: myproject
  script:
    - python manage.py test

deploy:
  stage: deploy
  image: docker:20.10.8
  services:
    - docker:20.10.8-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

